name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: Build & Test
    runs-on: macos-latest  # Mac required for iOS build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29'

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze Code
        run: flutter analyze

      - name: Run Tests
        run: flutter test

      - name: Build Android APK
        run: flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Set up Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Build iOS App
        run: flutter build ios --no-codesign

      - name: Archive iOS App
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          archive -archivePath build/Runner.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
          -archivePath build/Runner.xcarchive \
          -exportOptionsPlist ios/ExportOptions.plist \
          -exportPath build/ios

      - name: Upload iOS IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-ipa
          path: build/ios/Runner.ipa

  firebase-distribute:
    name: Firebase Distribution
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v4
        with:
          name: debug-apk
          path: app

      - name: Download IPA
        uses: actions/download-artifact@v4
        with:
          name: ios-ipa
          path: app

      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash

      - name: Authenticate Firebase
        run: echo "$FIREBASE_SERVICE_ACCOUNT" > firebase.json

      - name: Upload Android to Firebase
        run: firebase appdistribution:distribute app/app-debug.apk \
          --app ${{ secrets.FIREBASE_ANDROID_APP_ID }} \
          --groups testers \
          --token "$(cat firebase.json)"

      - name: Upload iOS to Firebase
        run: firebase appdistribution:distribute app/Runner.ipa \
          --app ${{ secrets.FIREBASE_IOS_APP_ID }} \
          --groups testers \
          --token "$(cat firebase.json)"
